name: CI
on: [push]
jobs:
  test_build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: logout
        run :
          docker logout
      - name: build docker image
        run : 
          docker build -t paulbonneville4/api-mldash:test .
      - name: run docker image
        run : 
          docker run -p 5000:5000 -d paulbonneville4/api-mldash:test 
      - name: Run tests
        run :
          pip install pytest
          run apt-get update -y
          run apt-get install python3 -y
          run apt-get install python3-pip -y
          run pip install joblib
          run pip install -U pytest
          run pip install flask
          run pip install -U scikit-learn
          pytest